services:
  db:
    container_name: db
    image: docker.io/mysql:8.4.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: findyourguide
    ports:
    - 3306:3306
    volumes:
    - data:/var/lib/mysql
  app:
    container_name: app
    image: find-your-guide:${APP_IMAGE_TAG}
    build: .
    ports:
    - ${APP_PORT}:80
    environment:
    - DB_URI=${DB_URI}
    - SECRET_KEY=${SECRET_KEY}
    - COPYRIGHT_URL=${COPYRIGHT_URL}
    - CLOUDINARY_URL=${CLOUDINARY_URL}
volumes:
  data: