services:
  db:
    container_name: db
    image: mysql:8.4.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
    - 3306:3306
  app:
    container_name: app
    image: find-your-guide:${APP_IMAGE_TAG}
    build: .
    ports:
    - ${APP_PORT}:80